import { useEffect, useState } from 'react';
import MenuCard from './MenuCard';
import { strongTitration, bufferAddition, approximationPercent } from '../../lib/chemistry-lab';
type Mode = 'menu' | 'titration' | 'buffer' | 'approximation';
export default function ChemistryLab({ onBack }: { onBack: () => void }) {
  const [mode,setMode]=useState<Mode>('menu');
  const [base,setBase]=useState(0),[guess,setGuess]=useState(''),[feedback,setFeedback]=useState('');
  const [added,setAdded]=useState(0),[kind,setKind]=useState<'acid'|'base'>('acid');
  const [initial,setInitial]=useState('0.10'),[ionized,setIonized]=useState('0.0020');
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key!=='Escape')return;e.preventDefault();e.stopImmediatePropagation();if(!e.repeat){if(mode==='menu')onBack();else setMode('menu');}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true);},[mode,onBack]);
  if(mode==='menu')return <MenuCard topic="화학 · 실험 원리 연습" question="어떤 실험을 연습할까요?" up={{label:'적정 곡선',onChoose:()=>setMode('titration')}} left={{label:'완충 성분 변화',onChoose:()=>setMode('buffer')}} right={{label:'5% 근사 검토',onChoose:()=>setMode('approximation')}} onBack={onBack} backLabel="학습 메뉴"><div className="observation-note glass"><p>필기의 조건으로 계산을 조작해요. 모형 결과와 실제 측정 기록은 구분해 주세요.</p></div></MenuCard>;
  const titration=strongTitration(.1,20,.1,base);
  const buffer=bufferAddition(10,10,added,kind);
  const approximation=initial.trim() && ionized.trim() ? approximationPercent(Number(initial),Number(ionized)) : null;
  const points=Array.from({length:301},(_,i)=>{const x=i/10;return `${30+x/30*270},${170-strongTitration(.1,20,.1,x).ph/14*140}`;}).join(' ');
  return <main className="swipe-app biology-app"><div className="biology-study"><header className="biology-header glass"><button className="glass-button" onClick={()=>setMode('menu')}>← 실험 선택</button><h1>화학 · {mode==='titration'?'적정 곡선':mode==='buffer'?'완충 성분 변화':'5% 근사 검토'}</h1></header><section className="biology-menu glass observation-panel">
    {mode==='titration'?<><h2>HCl 20 mL에 NaOH를 넣어 봐요</h2><p>25℃에서 0.10 M HCl 20 mL에 0.10 M NaOH를 넣는 이상적 모형이에요. 물의 이온화를 반영하며 부피는 합쳐진다고 가정해요.</p>
      <label className="observation-control">NaOH 첨가량 <output>{base.toFixed(1)} mL</output><input type="range" aria-label="NaOH 첨가량" min="0" max="30" step="0.1" value={base} onChange={e=>setBase(Number(e.target.value))}/></label>
      <button className="glass-button" onClick={()=>setBase(v=>Math.max(0,+(v-.1).toFixed(1)))}>0.1 mL 빼기</button> <button className="glass-button" onClick={()=>setBase(v=>Math.min(30,+(v+.1).toFixed(1)))}>0.1 mL 넣기</button>
      <svg viewBox="0 0 330 210" role="img" aria-label={`NaOH ${base.toFixed(1)} mL에서 pH ${titration.ph.toFixed(2)}인 적정 곡선`}><path d="M30 30V170H300" fill="none"/><polyline points={points} fill="none"/><circle cx={30+base/30*270} cy={170-titration.ph/14*140} r="4"/><text x="2" y="24">pH</text><text x="8" y="36">14</text><text x="15" y="173">0</text><text x="25" y="191">0</text><text x="200" y="191">20</text><text x="289" y="191">30</text><text x="92" y="207">NaOH 첨가량(mL)</text></svg>
      <p role="status">pH {titration.ph.toFixed(3)} · {Math.abs(base-titration.endpointMl)<1e-7?'중화점이에요.':base<titration.endpointMl?'산이 남아 있어요.':'염기가 남아 있어요.'}</p>
      <label className="observation-control">예상 중화점(mL)<input aria-label="예상 중화점" type="number" min="0" max="30" step="0.1" value={guess} onChange={e=>{setGuess(e.target.value);setFeedback('');}}/></label><button className="glass-button" onClick={()=>setFeedback(guess.trim()===''?'예상 부피를 입력해 주세요.':Math.abs(Number(guess)-20)<.05?'맞아요. H⁺와 OH⁻가 각각 2 mmol 반응해요.':'H⁺는 0.10 M×0.020 L=2 mmol이에요. 같은 몰수의 NaOH 부피를 구해 보세요.')}>예측 확인</button><p role="status">{feedback}</p><p>중화점 근처에서 첨가량을 0.1 mL씩 바꾸어 pH 변화가 커지는 이유를 관찰해요. 실제 센서값은 교반·온도·오차에 영향을 받아 모형과 다를 수 있어요.</p></>:mode==='buffer'?<><h2>산과 짝염기의 양을 추적해요</h2><p>처음 HA 10 mmol, A⁻ 10 mmol이에요. 아래 계산은 첨가 강산·강염기가 먼저 반응한 뒤의 몰수예요. 이후 평형에 따른 작은 변화는 생략해요.</p><fieldset><legend>첨가하는 물질</legend><label><input type="radio" name="addition" checked={kind==='acid'} onChange={()=>setKind('acid')}/> HCl</label> <label><input type="radio" name="addition" checked={kind==='base'} onChange={()=>setKind('base')}/> NaOH</label></fieldset><label className="observation-control">첨가량 <output>{added} mmol</output><input type="range" aria-label="완충계 첨가량" min="0" max="15" step="1" value={added} onChange={e=>setAdded(Number(e.target.value))}/></label><p>{kind==='acid'?'A⁻+H⁺→HA':'HA+OH⁻→A⁻+H₂O'}</p><p role="status">HA {buffer.ha} mmol · A⁻ {buffer.a} mmol · 과량 {kind==='acid'?'H⁺':'OH⁻'} {buffer.excess} mmol</p><p>{buffer.buffering?'두 성분이 남아 완충 작용을 할 수 있어요. 첨가량에 따라 pH가 조금 변해요.':'한 성분이 소진됐어요. 두 성분이 충분히 남는 완충 근사를 적용하면 안 돼요.'}</p><p>첨가량 2 mmol, 10 mmol, 12 mmol을 비교해 완충 용량을 설명해 보세요.</p></>:<><h2>C−x를 C로 근사해도 될까요?</h2><p>약산 평형식 Ka=x²/(C−x)에서 x/C×100이 5% 이하인지 확인해요. C는 초기 농도, x는 근사로 구한 이온화량이에요.</p><label className="observation-control">초기 농도 C(M)<input aria-label="초기 농도 C" type="number" step="any" min="0" value={initial} onChange={e=>setInitial(e.target.value)}/></label><label className="observation-control">이온화량 x(M)<input aria-label="이온화량 x" type="number" step="any" min="0" value={ionized} onChange={e=>setIonized(e.target.value)}/></label><p role="status">{approximation?`${approximation.percent.toFixed(2)}% · ${approximation.acceptable?'5% 기준에서 근사를 사용할 수 있어요.':'5%를 넘어요. 정확한 평형식을 풀어 주세요.'}`:'C>0, 0≤x≤C인 유효한 농도를 입력해 주세요.'}</p><p>이 검사는 C−x≈C의 타당성을 확인해요. 물의 이온화 무시 등 다른 가정까지 자동으로 검증하는 것은 아니에요.</p></>}
  </section></div></main>;
}
