// Converts every deck in data/ into the standard card format used by the Supabase database.
// Writes db/cards.json (readable copy) and db/seed.sql (paste into Supabase → SQL Editor after db/schema.sql).
// Usage: node scripts/export-cards.cjs
const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
require.extensions['.ts'] = (m, f) => m._compile(ts.transpileModule(fs.readFileSync(f, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, f);
const { subjectMenu } = require('../data/swipe-subjects.ts');

const root = path.join(__dirname, '..');
const SPLIT_GROUPS = new Set(['humanities']); // groups whose children are separate subjects (국어 · 사회 · 영어)

function teacherOf(deck) {
  const card = deck.cards[0];
  if (!card) return null;
  if (card.source?.teacher) return card.source.teacher;
  if (card.sourceSlide) return '황윤환T';
  const named = /([가-힣]{2,4}T)/.exec(deck.name + ' ' + (deck.fullName ?? ''));
  return named ? named[1] : null;
}

function sourceOf(card, teacher) {
  if (card.source) {
    const label = card.source.label ?? card.source.title.split('_')[0];
    return { source_label: [card.source.teacher ?? teacher, label].filter(Boolean).join(' · '), source_page: card.source.page, source_slide: null, source_url: card.source.url };
  }
  if (card.sourceSlide) return { source_label: `${teacher} 슬라이드`, source_page: null, source_slide: card.sourceSlide, source_url: null };
  const note = /^(.*?)\s*·\s*(\d+)쪽$/.exec(card.sourceNote ?? '');
  if (note) return { source_label: note[1], source_page: Number(note[2]), source_slide: null, source_url: null };
  if (card.sourceNote) return { source_label: card.sourceNote, source_page: null, source_slide: null, source_url: null };
  throw new Error(`No source for ${card.id}`);
}

const decks = [], cards = [];
function walk(group, parent) {
  for (const node of group.children) {
    if (node.kind === 'group') { walk(node, node); continue; }
    const subject = !parent || SPLIT_GROUPS.has(parent.id) ? node.name : parent.name;
    const teacher = teacherOf(node);
    decks.push({ id: node.id, subject, name: node.name, full_name: node.fullName ?? null, teacher, description: node.description, sort: decks.length });
    node.cards.forEach((card, i) => {
      const answer = card.answers[card.correct];
      const wrong = Object.entries(card.answers).filter(([d]) => d !== card.correct).map(([, text]) => text);
      cards.push({ id: card.id, deck_id: node.id, kind: 'choice', topic: card.topic, badge: card.subject ?? null, question: card.question, passage: card.passage ?? null, answer, wrong, criteria: [], explanation: card.explanation, ...sourceOf(card, teacher), sort: i });
    });
    (node.writtenQuestions ?? []).forEach((q, i) => {
      cards.push({ id: q.id, deck_id: node.id, kind: 'written', topic: q.topic, badge: null, question: q.question, passage: q.passage ?? null, answer: q.modelAnswer, wrong: [], criteria: q.criteria, explanation: '', ...sourceOf(q, teacher), sort: 1000 + i });
    });
  }
}
walk(subjectMenu, null);

const sql = v => v === null || v === undefined ? 'null'
  : typeof v === 'number' ? String(v)
  : Array.isArray(v) ? (v.length ? `array[${v.map(sql).join(', ')}]` : `'{}'::text[]`)
  : `'${String(v).replace(/'/g, "''")}'`;
const insert = (table, rows, cols) => rows.length ? `insert into public.${table} (${cols.join(', ')}) values\n${rows.map(r => `  (${cols.map(c => sql(r[c])).join(', ')})`).join(',\n')}\non conflict (id) do nothing;\n` : '';

const deckCols = ['id', 'subject', 'name', 'full_name', 'teacher', 'description', 'sort'];
const cardCols = ['id', 'deck_id', 'kind', 'topic', 'badge', 'question', 'passage', 'answer', 'wrong', 'criteria', 'explanation', 'source_label', 'source_page', 'source_slide', 'source_url', 'sort'];
const header = `-- Generated by scripts/export-cards.cjs from data/*.ts — ${decks.length} decks, ${cards.length} cards.\n-- Run after db/schema.sql. Safe to re-run: existing ids are skipped.\n\n`;
if (require.main === module) {
  fs.writeFileSync(path.join(root, 'db/cards.json'), JSON.stringify({ decks, cards }, null, 2) + '\n');
  fs.writeFileSync(path.join(root, 'db/seed.sql'), header + insert('decks', decks, deckCols) + '\n' + insert('cards', cards, cardCols));
  console.log(`Exported ${decks.length} decks and ${cards.length} cards (${cards.filter(c => c.kind === 'written').length} written) to db/cards.json and db/seed.sql.`);
}
module.exports = { decks, cards };
